import express from 'express';

const router = express.Router();

// Route to get the images by polling this path, which is being generated by the model
router.get("/", (req, res) => {
    
});

export default router; 